# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rbs` gem.
# Please instead update this file by running `bin/tapioca gem rbs`.


# source://rbs//lib/rdoc/discover.rb#8
class RDoc::Parser::RBS < ::RDoc::Parser
  # source://rbs//lib/rdoc/discover.rb#10
  def scan; end
end
