on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/test.yaml"
      - "lib/**"
      - "test/**"
      - "Gemfile"
      - "Gemfile.lock"
      - "rager.gemspec"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - "3.3"
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      REPLICATE_API_KEY: ${{ secrets.REPLICATE_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - uses: actions/cache@v4
        with:
          path: test/fixtures/http
          key: ${{ runner.os }}-ruby-${{ matrix.ruby }}-fixtures-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-ruby-${{ matrix.ruby }}-fixtures-

      - run: bundle exec rake test

      - run: bundle exec srb tc
        if: success() || failure()

      - run: bundle exec standardrb
        if: success() || failure()
